apiVersion: v1
appVersion: "1.0"
description: A Helm chart for HMCTS Kubernetes Job / CronJob
name: job
version: 0.6.0
keywords:
  - Job
  - CronJob

dependencies:
  - name: library
    version: 0.4.0
    repository: https://hmctspublic.azurecr.io/helm/v1/repo/
