{{ if or (and .Values.overrideKind (eq .Values.overrideKind "Job")) (and (not .Values.overrideKind) (and .Values.global.job.kind (eq .Values.global.job.kind "Job"))) }}
---
apiVersion: batch/v1
kind: Job
{{ include "job.metadata" .}}
{{ include "job.spec" .}}
  {{- end}}